### ISSUE TITLE
rake Thor::Base error after adding guard-rspec to Rails 4 mountable engine gemspec

### ISSUE THREAD

**Issue by bbugh** [guard/guard-rspec#258]
I am using a ```--mountable``` Rails engine and rspec. If I add this to my gemspec and run bundle ```s.add_development_dependency 'guard-rspec'``` then the ```rake``` command (with or without bundle exec) does this:

```
~/projects/project_name(branch:master*) » rake
rake aborted!
NameError: uninitialized constant Thor::Base
/Users/brian_b/projects/project_name/Rakefile:22:in `<top (required)>'
(See full trace by running task with --trace)
```

If I instead specify it with ``` s.add_dependency 'guard-rspec'``` then it will work fine. This is obviously not optimal, as clients shouldn't have to install guard-rspec to run the engine.

REPRODUCTION: This is with a brand new fresh project with no modifications, after following this guide. http://viget.com/extend/rails-engine-testing-with-rspec-capybara-and-factorygirl The instructions can be followed here for an exact replication of the issue, just add guard-rspec as a development_dependency.

**Comment by e2** [comment]
Seems fixed (closed: https://github.com/bundler/bundler/issues/3205) - please reopen/comment if not. Thanks!

**Comment by wdiechmann** [comment]
@bbugh  your trick (moving Bundler::GemHelper.install_tasks to the top) did the trick for me, with regards to a Rails gem, using minitest
