### ISSUE TITLE
Guard is running wrong specs when used with spring

### ISSUE THREAD

**Issue by ibrahima** [guard/guard-rspec#272]
I'm not sure if this is a guard-rspec issue, a spring issue, or a guard issue, but I've got a (private) Rails 3 project that I'm using Spring and Rspec3 with (well, I upgraded to these in an effort to modernize the project a bit and eventually move to Rails 4). When I use the default Guardfile it works fine without Spring, but when I use spring like

`guard :rspec, all_after_pass: false, cmd: 'spring rspec spec -f doc' do`

and then edit a file, it doesn't re-run the specs that are relevant to that file, it instead runs a fixed subset of unrelated specs every time I modify files. This defeats the purpose of Spring, needless to say. Any ideas on how I can figure out what's going on or try to fix it? It seems like if this happened to everyone no one would use spring with guard-rspec but it seems like it works for some people. Apologies if this is not the proper place for this kind of issue.

Relevant gem versions:

guard-rspec (4.2.10)
rspec 3.0.0
rspec-core 3.0.2
rspec-rails 3.0.1
guard 2.6.1

Platform is Linux 3.13 on Ubuntu 14.04.

**Comment by e2** [comment]
I'm closing this, because it seems outdated (given the releases that happened since).

If not, please open a new issue if need.
