### ISSUE TITLE
Push a new release?

### ISSUE THREAD

**Issue by jasonmk** [guard/guard-rspec#319]
Hi,

Any chance you can push out a new release? Focus mode is broken in 4.5.0 with RSpec 3.1+. Master works thanks to changes in the rspec formatter.

Thanks!

**Comment by e2** [comment]
Thanks for reminding me - I was waiting until a few things were cleared up (some hard-to-debug crashes occuring), but I'll release as soon as I add some debugging helpers.

**Comment by e2** [comment]
Done (4.5.1) - let me know if you have any issues.
