### ISSUE TITLE
commandline showing a warning regarding not using bundler while running guard init

### ISSUE THREAD

**Issue by flyingboy007** [guard/guard-rspec#346]
In my rails app am getting this warning while running <i>"guard init rspec"</i>

> Warning: you have a Gemfile, but you're not using bundler or
> RUBYGEMS_GEMDEPS
> 14:54:15 - INFO - Writing new Guardfile to
> /home/ubuntu/railsprojects/sillyfish/Guardfile 14:54:16 - INFO - rspec
> guard added to Guardfile, feel free to edit it

I dont understand why its showing. Is this ok to ignore this warning?

Here is my gemfile

    source 'https://rubygems.org'
    
    
    gem 'rails', '4.2.4'
    gem 'pg'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    group :development, :test do
      gem 'rspec-rails', '3.3.3'
      gem 'guard-rspec', require: false
      gem 'spring-commands-rspec'
      gem 'byebug'
    end
    
    group :development do
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end
    
    group :test do
      gem 'capybara', '2.5.0'
    end
    
    
    #custom gems
    gem 'puma'
    gem 'bootstrap-sass', '~> 3.3.5'
    gem 'devise', '~> 3.5.2'

**Comment by e2** [comment]
The warning should probably be better, but it means you should use bundler with every command: `bundle exec guard init rspec`.

**Comment by flyingboy007** [comment]
Ok thanks.

**Comment by metacoder87** [comment]
Thank you I was getting the same error when launching guard with foreman. I added 'bundle exec' before the guard command in my Procfile and the error is gone. Been searching for hours on this. Thanks again.

**Comment by metacoder87** [comment]
> The warning should probably be better, but it means you should use bundler with every command: `bundle exec guard init rspec`.

Thank you I was getting the same error when launching guard with foreman. I added 'bundle exec' before the guard command in my Procfile and the error is gone. Been searching for hours on this. Thanks again.
