### ISSUE TITLE
Getting bundler to resolve correctly with Rails 5 and RSpec 3.5.0 beta

### ISSUE THREAD

**Issue by colszowka** [guard/guard-rspec#360]
Hey, just came here for documentation purposes.

In my Rails 5.0.0.beta3 app, I ran into an issue when trying to upgrade to the [rspec-rails 3.5.0.beta1 version](https://github.com/rspec/rspec-rails/issues/1549), with bundler failing to resolve things correctly for me.

What I had in my Gemfile:

```
gem 'rspec-rails', '~> 3.5.0.beta1'
gem 'guard-rspec', '~> 4.6', require: false
```

This failed to resolve a matching version for `rspec` and `rspec-core`. Not sure if this might be an actual issue in the bundler resolver, I'll think about filing an issue there as well, but regardless, being explicit about what I want solved the problem for me:

```
gem 'rspec', '~> 3.5.0.beta1'
gem 'rspec-core', '~> 3.5.0.beta1'
gem 'rspec-rails', '~> 3.5.0.beta1'
gem 'guard-rspec', '~> 4.6', require: false
```

**Comment by colszowka** [comment]
...and closing right away, this is just to help fellow future googlers.

**Comment by marcusroberts** [comment]
Thank you, that just solved the exact same problem for me.

**Comment by e2** [comment]
I've updated the README to give a quick cheatsheet on using RSpec beta: https://github.com/guard/guard-rspec/blob/master/README.md#installing-with-beta-versions-of-rspec
