### ISSUE TITLE
rails 5 can't run because dependent conflict

### ISSUE THREAD

**Issue by tianlu1677** [guard/guard-rspec#367]
When I use Rails 5 .

This is a error. What should I do ?
```ruby
Bundler could not find compatible versions for gem "rspec-core":
  In snapshot (Gemfile.lock):
    rspec-core (= 3.5.0.beta3)

  In Gemfile:
    guard-rspec (= 4.6.5) was resolved to 4.6.5, which depends on
      rspec (< 4.0, >= 2.99.0) was resolved to 2.99.0, which depends on
        rspec-core (~> 2.99.0)

    rspec-rails (~> 3.5.0.beta1) was resolved to 3.5.0.beta3, which depends on
      rspec-core (= 3.5.0.beta3)

```

**Comment by e2** [comment]
I'm ony phone so I can't find it now, but there was an issue with
supporting rails 5. There should be a branch for it somewhere. I think just
newer rspec has to be released first. I'd love to merge any
fixes/workarounds for this, though.

**Comment by e2** [comment]
You'll need to specify the rspec-* beta gems explicitly, because Bundler doesn't install them by default, e.g.

```ruby
gem 'rspec '~> 3.5.0.beta3'
gem 'rspec-core '~> 3.5.0.beta3'
gem 'rspec-expectations '~> 3.5.0.beta3'
gem 'rspec-mock '~> 3.5.0.beta3'
gem 'rspec-support '~> 3.5.0.beta3'
gem 'rspec-rails '~> 3.5.0.beta3'
```

Let me know if that worked.

**Comment by e2** [comment]
I've updated the README to give a quick cheatsheet on using RSpec beta: https://github.com/guard/guard-rspec/blob/master/README.md#installing-with-beta-versions-of-rspec

**Comment by KelseyDH** [comment]
@e2 Any update for this now that `rspec-rails` 3.5.2 is the latest version?
