### ISSUE TITLE
Incompatible with RSpec 3.5.0.beta3 

### ISSUE THREAD

**Issue by maxcal** [guard/guard-rspec#372]
Trying to setup a Rails 5 app (5.0.0.rc1) with rspec-rails (3.5.0.beta3) and guard-rspec (4.7.0) however bundler cannot find a compatible version of guard-rspec.

```
Bundler could not find compatible versions for gem "rspec-core":
  In snapshot (Gemfile.lock):
    rspec-core (= 3.5.0.beta3)

  In Gemfile:
    guard-rspec (~> 4.7.0) was resolved to 4.7.0, which depends on
      rspec (< 4.0, >= 2.99.0) was resolved to 2.99.0, which depends on
        rspec-core (~> 2.99.0)

    rspec-rails (= 3.5.0.beta3) was resolved to 3.5.0.beta3, which depends on
      rspec-core (= 3.5.0.beta3)
```

I believe this may be due to the way that the dependency is declared in the gemspec:
```
s.add_dependency "rspec", ">= 2.99.0", "< 4.0"
```

**Comment by freeatnet** [comment]
Hey @maxcal! I've run into the same issue. It appears that the constraints are too lax in one of the gems for Bundler to resolve them correctly. Keeping in mind this is edge stuff, I've added
```gem "rspec", "3.5.0.beta3"```
in my Gemfile, which fixed the version resolution.

**Comment by e2** [comment]
Thanks for reporting this, and thanks @freeatnet for the help.

I've updated the README to give a quick cheatsheet on how to resolve RSpec beta dependencies here:

https://github.com/guard/guard-rspec/blob/master/README.md#installing-with-beta-versions-of-rspec
