### ISSUE TITLE
Rubygems dependency problem

### ISSUE THREAD

**Issue by budmc29** [guard/guard-rspec#389]
Version 4.7.3 of guard-rspec has no ruby dependency on rubygems, but when you try and install it you get:

```
An error occurred while installing ruby_dep (1.5.0), and Bundler cannot continue.
Make sure that `gem install ruby_dep -v '1.5.0'` succeeds before bundling.
```

and ruby_dep -v 1.5.0 has a dependency on ruby 2.2+

```
ERROR:  Error installing ruby_dep:
        ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

Solution: Add ruby dependency to rubygems.

**Comment by adiakritos** [comment]
I'm having the same issue. How can I resolve in the time being? I'm running on Ruby 2.2.3

**Comment by budmc29** [comment]
Try a version of guard-rspec previous to 4.7.3 if upgrading to 2.2.5 is not an option.

**Comment by adiakritos** [comment]
all good. I upgraded to Ruby 2.3.0 and it works just fine. Thanks!

**Comment by GraySmith00** [comment]
same problem here, I'm on c9 2.1.5, tried upgrading Ruby to 2.2, 2.2.5, 2.3 but whenever i do that the bundle install gets 'killed' :(

**Comment by budmc29** [comment]
What is the error message?
